/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog. */

#ifndef DEFINES_H_
#define DEFINES_H_
#include "flags.h"


#define UMIN(a, b)		((a) < (b) ? (a) : (b))
#define UMAX(a, b)		((a) > (b) ? (a) : (b))
#define URANGE(a, b, c)		((b) < (a) ? (a) : ((b) > (c) ? (c) : (b)))

#define args( list )			list
#define DECLARE_DO_FUN( fun )\
	DO_FUN	  fun
//	CONST_DO_FUN	fun
#define DECLARE_SPEC_FUN( fun )		SPEC_FUN  fun
#define DECLARE_SPELL_FUN( fun )	SPELL_FUN fun
#define DECLARE_CON_FUN( fun )		CON_FUN	  fun

#define DEF_DO_FUN( name )          void do_##name( CHAR_DATA *ch, char *argument )

/*
 * * String and memory management parameters.
 * */
#define MAX_CMD_HASH		126 /* Max command hash */
#define HASHSTR				/* use string hashing */
#define MAX_KEY_HASH		1024    /*2048 -> 1024*/
#define MAX_STRING_LENGTH	16258   /*4096 -> 8129 -> 16258 */  /* buf */
#define MAX_INPUT_LENGTH	512 /*1024 -> 512 */        /* arg */
#define MAX_INBUF_SIZE		1024
#define MSL					MAX_STRING_LENGTH   /*Thanos: dla wygody*/
#define MIL					MAX_INPUT_LENGTH
#define MFL					256     /* Trog: maksymalna dlugosc nazwy pliq (MAX_FILENAME_LENGTH) */

/*
 * * Game parameters.
 * * Increase the max'es if you add more of something.
 * * Adjust the pulse numbers to suit yourself.
 * */
#define MAX_EXP_WORTH           10000
#define MIN_EXP_WORTH           25

#define MAX_REXITS              20  /* Maximum exits allowed in 1 room */
#define MAX_SKILL               277
#define MAX_ABILITY             8
#define MAX_LEVEL               105
#define MAX_CLAN                50
#define MAX_PLANET              100
#define MAX_SHIP                1000
#define MAX_BOUNTY              255
#define MAX_GOV                 255
#define MAX_HERB                20
#define MIN_BARGAIN_PRICE       50  /* poni¿ej tej warto¶ci moby       */
                                    /* nie bêd± siê targowaæ -- Thanos */
#define MAX_BARGAIN             20  /* wiêcej procent nie utargujesz */
#define MAX_KNOWN( ch )         ( ch )->perm_wis*5  //Tanglor i poprawka Ganisa

#define MAX_KILLTRACK		20		/* track mob vnums killed */


#define send_to_char			send_to_char_color
#define send_to_pager			send_to_pager_color

/*Thanos*/
#define is_number			adv_is_number


/* skrocone nazwy typow */
#undef	SK
#undef	CO
#undef	ST
#undef	CD
#undef	MID
#undef	OD
#undef	OID
#undef	RID
#undef	SF
#undef	BD
#undef	CL
#undef	EDD
#undef	RD
#undef	ED
#undef	BOD
#undef	SD
#undef	PD
#undef	CRD
#undef	ID
#undef	MD
#undef	REQ
#undef	AFF
#undef	SHD
#undef	RHD

#define CD			CHAR_DATA
#define MID			MOB_INDEX_DATA
#define OD			OBJ_DATA
#define OID			OBJ_INDEX_DATA
#define RID			ROOM_INDEX_DATA
#define SF			SPEC_FUN
#define BD			BOARD_DATA
#define CL			CLAN_DATA
#define EDD			EXTRA_DESCR_DATA
#define RD			RESET_DATA
#define ED			EXIT_DATA
#define ST			SOCIALTYPE
#define CO			COUNCIL_DATA
#define DE			DEITY_DATA
#define SK			SKILLTYPE
#define SH			SHIP_DATA
#define PD			PLANET_DATA
#define BOD			BOUNTY_DATA
#define SD			SPACE_DATA
#define CRD			CRIME_DATA
#define AS			ASTRO_DATA /*Alde*/
#define ID			INFORM_DATA /*Than*/
#define MD			MEMBER_DATA
#define REQ			REQUIREMENT_DATA
#define AFF			AFFECT_DATA
#define SHD			SHOP_DATA
#define RHD			REPAIR_DATA

/* moveed to .mudrc
#define SQL_CONN_STRING	"hostaddr=127.0.0.1 dbname=mud user=mud password=bleblebleasda"
*/

#define HOTEL_SAFE_TIME			60 /*Czas (sekundy) przez jaki po wej¶ciu do gry gracz jest bezpieczny w hotelu*/
#define HOTEL_SAFE_COOLDOWN		300 /*Ile gracz musi byæ poza gr±, aby byæ w hotelu bezpiecznym po wej¶ciu do gry*/

#endif //DEFINES_H_
