/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef AUCTION_DATA_H_
#define AUCTION_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	auction_data
{
	AUCTION_DATA		* next;			//w koncu mozemy miec kilka aukcji
	AUCTION_DATA		* prev;
	BETS_PROGRES		* first;		//lista licytuj±cych
	BETS_PROGRES		* last;

	auction_type		type;			/*!< typ sprzedawanego towaru */
	char				* planet;		/*!< planeta na jakiej toczy sie licytacja */
	OBJ_DATA			* item;			/*!< a pointer to the item */
	char				* stock_name;	/*!< nazwa licytowanego przedmiotu - dla notek inf */
	char				* seller_name;
	char				* desc;			/*!< krótki opis gracza sprzedaj±cego */
	int64				buy_out_now;	//stawka za jaka mozna natychmiast kupic dany przedmiot
	int64				starting_price;
	int64				bet;			// najwyzsza aktualna stawka
	int					bidders_count;	//ilu licytantow
	int64				quantity;		/*!< iloæ sprzedawnych towarów*/

	int					duration;		/*!< czas trwania aukcji w godzinach */
	time_t				start_time;
	time_t				end_time;		//kiedy koniec
	bool				item_collected; //czy licytujacy dostal przedmiot
	bool				payment_collected;	//czy licytator dostal kase
	bool				notes_send;			//czy wyslalismy juz notki z infomacjami
	bool				max_cash_auction;	/*!< czy chce by zarobiæ jak najwiêcej na aukcji, czy sprzedaæ caly towar */
};

#endif //AUCTION_DATA_H_

