/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef BOUNTY_DATA_H_
#define BOUNTY_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	bounty_data
{
	BOUNTY_DATA			* next;
	BOUNTY_DATA			* prev;
	char				* target;
	long int			amount;
	int					type;
};

#endif //BOUNTY_DATA_H_

