/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef CHAPTER_INDEX_DATA_H_
#define CHAPTER_INDEX_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct chapter_index_data
{
	CHAPTER_INDEX_DATA	* prev;
	CHAPTER_INDEX_DATA	* next;
	QUEST_CMND_DATA		* first_init_cmd;
	QUEST_CMND_DATA		* last_init_cmd;
	QUEST_CMND_DATA		* first_event;
	QUEST_CMND_DATA		* last_event;
	QUEST_ACTION_DATA	* first_action;
	QUEST_ACTION_DATA	* last_action;
	char				* name;
	int					type;
};

#endif //CHAPTER_INDEX_DATA_H_

