/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef CLONING_DATA_H_
#define CLONING_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct cloning_data
{
	CLONING_DATA		* next;
	CLONING_DATA		* prev;
	ROOM_INDEX_DATA		* entrance;
	ROOM_INDEX_DATA		* cylinder;
	ROOM_INDEX_DATA		* leaving;
};

#endif //CLONING_DATA_H_

