/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef DOCK_DATA_H_
#define DOCK_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct dock_data
{
	DOCK_DATA			* next;
	DOCK_DATA			* prev;
	char				* name;
	int					vnum;
	float				capacity;
	int					hidden;
	int					quest_id;
	bool				busy;
};

#endif //DOCK_DATA_H_

