/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef FEVENT_DATA_H_
#define FEVENT_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct fevent_data
{
	FEVENT_DATA	*next;
	FEVENT_DATA	*prev;
	fe_trigger	trigger;
	int64		attr[FE_MAX_ATTR];
	char		*sattr;
};

#endif //FEVENT_DATA_H_

