/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef FOR_DATA_H_
#define FOR_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct for_data
{
	CHAR_DATA			* fOwner;		// wska¼nik na wykonawcê 'for'
	CHAR_DATA			* fVictim;	// wska¼nik na moba/gracza aktualnie 'obs³ugiwanego'
	AREA_DATA			* fArea;		// wska¼nik na krainkê aktualnie 'obs³ugiwan±'
	int					fRoom;		// vnum pokoju aktualnie 'obs³ugiwanego'
	char				* command;	// komenda
	bool				fMobs;		// czy for dotyczy mobów
	bool				fMortals;	// czy for dotyczy graczy
	bool				fGods;		// czy for dotyczy immosów
	bool				fEverywhere;// czy mo¿e wszystkich lokacji muda
	bool				fAreaMobs;	// albo mobów w krainie
	bool				fAreaRooms;	// albo lokacji w krainie
	bool				fStopped;	// czy zatrzymana
	int					fCount;		// ilo¶æ powtórzeñ
};

#endif //FOR_DATA_H_

