/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef GODLIST_DATA_H_
#define GODLIST_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	godlist_data
{
	GOD_DATA			* next;
	GOD_DATA			* prev;
	int					level;
	int					low_r_vnum;
	int					hi_r_vnum;
	int					low_o_vnum;
	int					hi_o_vnum;
	int					low_m_vnum;
	int					hi_m_vnum;
};

#endif //GODLIST_DATA_H_

