/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef GUARD_DATA_H_
#define GUARD_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct guard_data
{
	GUARD_DATA			* next;
	GUARD_DATA			* prev;
	GUARD_DATA			* next_on_planet;
	GUARD_DATA			* prev_on_planet;
	ROOM_INDEX_DATA		* reset_loc;
	PLANET_DATA			* planet;
	CHAR_DATA			* mob;
};

#endif //GUARD_DATA_H_

