/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef KNOWN_CHAR_DATA_H_
#define KNOWN_CHAR_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct known_char_data
{
	KNOWN_CHAR_DATA		* prev;
	KNOWN_CHAR_DATA		* next;
	RACE_DATA			* race;
	char				* name;
//	int					race;
	int					is_remembered;
	int					sex;
};

#endif //KNOWN_CHAR_DATA_H_

