/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef LANG_DATA_H_
#define LANG_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	lang_data
{
	LANG_DATA			* next;
	LANG_DATA			* prev;
	LCNV_DATA			* first_precnv;
	LCNV_DATA			* last_precnv;
	LCNV_DATA			* first_cnv;
	LCNV_DATA			* last_cnv;
	char				* name;
	char				* alphabet;
	char				* deny_text;
	int					max_learn;		/* na ile % maksymalnie gracz moze sie nauczyc */
	int					max_practice;	/* do ilu % maksymalnie gracz moze wypraktykowac */
	int					min_int;		/* minimalna wartosc inteligencji */
									/* wymaganej do chociaz 1% znajomosci */
	int					difficulty;
};

#endif //LANG_DATA_H_

