/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef MADULE_DATA_H_
#define MADULE_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct madule_data
{
	MODULE_DATA			* next;
	MODULE_DATA			* prev;
	int					type;
	int					value;
	int					value2;
	int					value3;
	int					size;
	int					status;
	int					crs;
	int					cost;
	int					vnum;
	char				* spyname;
	int					timer;
};

#endif //MADULE_DATA_H_

