/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef MATERIAL_DATA_H_
#define MATERIAL_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct material_data	//Tanglor
{
	MATERIAL_DATA			* next; /*!< n±stêpny materia³ na li¶cie*/
	MATERIAL_DATA			* prev; /*!< poprzedni materia³ na li¶cie*/
	char					* name; /*!< nazwa materia³u*/
	char					* desc; /*!< opis materia³u*/
	material_type			type;	/*!< typ materia³u - ruda, stop, itp*/
	material_rarity			rarity; /*!< jak czêsto wystêpuje*/
//  MAT_TYPE		    type;
//  TRANS_REQ		    trans;
	bool					can_mine;	/*!< czy jest wydobywany czy produkowany*/
	int64					price;		/*!< bazowa cena*/
	int64					min_price;	/*!< minimalna cena*/
	int64					max_price;	/*!< maksymalna cena*/
};

#endif //MATERIAL_DATA_H_

