/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef MOB_PROG_ACT_LIST_H_
#define MOB_PROG_ACT_LIST_H_
#include "../defines.h"
#include "../typedefs.h"

struct	mob_prog_act_list
{
	MPROG_ACT_LIST		* next;
	char				* buf;
	CHAR_DATA			* ch;
	OBJ_DATA			* obj;
	void				* vo;
};

#endif //MOB_PROG_ACT_LIST_H_

