/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef NOTE_DATA_H_
#define NOTE_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	note_data
{
	NOTE_DATA			* next;
	NOTE_DATA			* prev;
	char				* sender;
	char				* real_sender;	// jesli inny ni¿ nick sendera (Thanos)
	char				* date;
	char				* to_list;
	char				* subject;
	int					voting;
	char				* yesvotes;
	char				* novotes;
	char				* abstentions;
	char				* text;
	time_t				stamp; //added by Thanos
};

#endif //NOTE_DATA_H_

