/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef OBJ_DATA_H_
#define OBJ_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	obj_data
{
	OBJ_DATA			* next;
	OBJ_DATA			* prev;
	OBJ_DATA			* next_content;
	OBJ_DATA			* prev_content;
	OBJ_DATA			* first_content;
	OBJ_DATA			* last_content;
	OBJ_DATA			* in_obj;
	CHAR_DATA			* carried_by;
	EXTRA_DESCR_DATA	* first_extradesc;
	EXTRA_DESCR_DATA	* last_extradesc;
	AFFECT_DATA			* first_affect;
	AFFECT_DATA			* last_affect;
	REQUIREMENT_DATA	* first_requirement;
	REQUIREMENT_DATA	* last_requirement;
	OBJ_INDEX_DATA		* pIndexData;
	ROOM_INDEX_DATA		* in_room;
	VAR_DATA			* variables; /* Ratm - zmienne do mob_programow */
	char				* armed_by;
	char				* name;
	char				* description;
	char				* action_desc;
	int					item_type;
	int64				extra_flags;
	int64				force_flags; /*Need more bitvectors for spells - Scryn*/
	int64				wear_flags;
	int					blaster_setting;
	MPROG_ACT_LIST		* mpact;		/* mudprogs */
	int					mpactnum;	/* mudprogs */
	int					mpscriptrun;		/* Thanos - latwiej szukaæ proga */
	int					wear_loc;
	int					weight;
	int					cost;
	int					level;
	int					timer;
	int					value[6];
	int					count;		/* support for object grouping */
	int					serial;		/* serial number	       */
	char				* przypadki[6]; //added by Thanos
	int					gender;		//adedd by Thanos
	QUEST_DATA			* inquest;
	char				* owner_name;	/* personale -- Thanos */
};

#endif //OBJ_DATA_H_

