/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef OBJ_INDEX_DATA_H_
#define OBJ_INDEX_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	obj_index_data
{
	OBJ_INDEX_DATA		* next;
	OBJ_INDEX_DATA		* next_sort;
	EXTRA_DESCR_DATA	* first_extradesc;
	EXTRA_DESCR_DATA	* last_extradesc;
	AFFECT_DATA			* first_affect;
	AFFECT_DATA			* last_affect;
	REQUIREMENT_DATA	* first_requirement;
	REQUIREMENT_DATA	* last_requirement;
	MPROG_DATA			* mudprogs;		  /* objprogs */
	int64				progtypes;		/* objprogs */
	char				* name;
	char				* description;
	char				* action_desc;
	int					vnum;
	int					level;
	int					item_type;
	int64				extra_flags;
	int64				force_flags; /*Need more bitvectors for spells - Scryn*/ /* To to na 95% jest do wyrzucenia */
	int64				wear_flags;
	int					count;
	int					weight;
	int					cost;
	int					value[6];
	int					serial;
	int					layers;
	int					rent;			/* Unused */
	char				* przypadki[6]; //added by Thanos
	int					gender;			//adedd by Thanos
};

#endif //OBJ_INDEX_DATA_H_

