/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef QUEST_MOB_DATA_H_
#define QUEST_MOB_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	quest_mob_data
{
	QUEST_MOB_DATA		* next;
	QUEST_MOB_DATA		* prev;
	CHAR_DATA			* mob;
	bool				invited;
	int					vnum;
};

#endif //QUEST_MOB_DATA_H_

