/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef RACE_TYPE_H_
#define RACE_TYPE_H_
#include "../defines.h"
#include "../typedefs.h"

struct	race_type
{
	char				race_name[17];	/* Race name			*/
	int					affected;		/* Default affect bitvectors	*/
	int					str_plus;		/* Str bonus/penalty		*/
	int					dex_plus;		/* Dex	    "			*/
	int					wis_plus;		/* Wis	    "			*/
	int					int_plus;		/* Int	    "			*/
	int					con_plus;		/* Con	    "			*/
	int					cha_plus;		/* Cha	    "			*/
	int					lck_plus;		/* Lck	    "			*/
	int					frc_plus;		/* Frc	    "			*/
	int					hit;
	int					mana;
	int					resist;
	int					suscept;
	int					class_restriction;	/* Flags for illegal classes	*/
	int					language;			/* Default racial language	*/
	char				* przypadki	[6];	/*Added by Thanos*/
	char				* inflectsFemale	[6];	// Pixel: przypadkiF
	bool				pc_avail;
};

#endif //RACE_TYPE_H_

