/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef ROOM_INDEX_DATA_H_
#define ROOM_INDEX_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	room_index_data
{
	ROOM_INDEX_DATA		* next;
	ROOM_INDEX_DATA		* next_sort;
	ROOM_INDEX_DATA		* next_on_ship;		//Thanos
	ROOM_INDEX_DATA		* prev_on_ship;		//Thanos
	SHIP_DATA			* ship;		//Thanos
	CHAR_DATA			* first_person;
	CHAR_DATA			* last_person;
	OBJ_DATA			* first_content;
	OBJ_DATA			* last_content;
	EXTRA_DESCR_DATA	* first_extradesc;
	EXTRA_DESCR_DATA	* last_extradesc;
	AREA_DATA			* area;
	EXIT_DATA			* first_exit;
	EXIT_DATA			* last_exit;
	SHIP_DATA			* first_ship;
	SHIP_DATA			* last_ship;
	RESET_DATA			* first_reset;
	RESET_DATA			* last_reset;
	VAR_DATA			* variables; /* Ratm - zmienne do mob_programow */
	char				* name;
	char				* homename;
	char				* description;
	char				* nightdesc;
	int					vnum;
	int					svnum;			/* Thanos: constrship */
	int64				room_flags;
	MPROG_ACT_LIST		* mpact;	       /* mudprogs */
	int					mpactnum;	     /* mudprogs */
	MPROG_DATA			* mudprogs;	       /* mudprogs */
	int64				progtypes;	     /* mudprogs */
	int					mpscriptrun;		/* Thanos - latwiej szukaæ proga */
	int					light;
	int					sector_type;
	int					tele_vnum;
	int					tele_delay;
	int					tunnel;		/* max people that will fit */
	/* Trog: clan stuff */
	RID					* next_in_hq;
	RID					* prev_in_hq;
	HQ_ROOM				clan_room;
};

#endif //ROOM_INDEX_DATA_H_

