/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef SCRIPT_DATA_H_
#define SCRIPT_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	script_data
{
	SCRIPT_DATA			* next;
	SCRIPT_DATA			* prev;
	CHAR_DATA			* m_owner;
	OBJ_DATA			* o_owner;
	ROOM_INDEX_DATA		* r_owner;
	CHAR_DATA			* victim;
	CHAR_DATA			* random;
	OBJ_DATA			* object;
	void				* vo;
	char				* command;
	int					position;	/* pozycja aktualnie wykonywanej komendy  */
	int					curr_line;	/* numer aktualnie wykonywanej linii */
	int					trigger;	/* Numer skryptu (trigger przy script_prog) */
	int					prog_nr;	/* Numer na liscie progów moba */
	bool				active;
};

#endif //SCRIPT_DATA_H_

