/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef SHOP_DATA_H_
#define SHOP_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	shop_data
{
	SHOP_DATA			* next;			/* Next shop in list		*/
	SHOP_DATA			* prev;			/* Previous shop in list	*/
	int					keeper;			/* Vnum of shop keeper mob	*/
	int					buy_type [MAX_TRADE];	/* Item types shop will buy	*/
	int					profit_buy;		/* Cost multiplier for buying	*/
	int					profit_sell;	/* Cost multiplier for selling	*/
	int					open_hour;		/* First opening hour		*/
	int					close_hour;		/* First closing hour		*/
	int64				flags;			/* Trog */
};

#endif //SHOP_DATA_H_

