/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef SPACE_DATA_H_
#define SPACE_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct space_data
{
	SPACE_DATA			* next;
	SPACE_DATA			* prev;
	SHIP_DATA			* first_ship;
	SHIP_DATA			* last_ship;
	ASTRO_DATA			* first_astro;	/*Alde*/
	ASTRO_DATA			* last_astro;		/*Alde*/
	MISSILE_DATA		* first_missile;
	MISSILE_DATA		* last_missile;
	PLANET_DATA			* first_planet;
	PLANET_DATA			* last_planet;
	STAR_DATA			* first_star;
	STAR_DATA			* last_star;
	MOON_DATA			* first_moon;
	MOON_DATA			* last_moon;
	RESET_DATA			* first_reset;	// Thanos
	RESET_DATA			* last_reset;		// Thanos
	char				* filename;
	char				* name;
	char				* resetmsg;		// Thanos
	int					age;			// Thanos
	int					reset_frequency;// Thanos
	float				xpos;
	float				ypos;
	int					crash;
	int					hidden;
	int					version;
	char				* description;
	char				* description2;
	char				* description3;
	int64				flags;
};

#endif //SPACE_DATA_H_

