/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef STOCK_EXCHANGE_DATA_H_
#define STOCK_EXCHANGE_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct stock_exchange_data	//gielda materialów
{
	STOCK_EXCHANGE_DATA	* next;	    /*!< wskaznik na kolejna gielda */
	STOCK_EXCHANGE_DATA	* prev;	    /*!< wskaznik na poprzednia gielde*/
    PLANET_DATA *		pPlanet;  /*!< planeta na której znajduje siê dana gie³da*/
	AUCTION_DATA *		first;	  /*!< pierwsza z toczacych sie licytacji*/
	AUCTION_DATA *		last;	  /*!< ostatnia z tocz¹cych sie licytacji*/
	AUCTION_DATA *		first_new_offert;	/*!< pierwsza z nowych ofert*/
	AUCTION_DATA *		last_new_offert;	/*!< ostatnia z nowych ofert*/
};

#endif //STOCK_EXCHANGE_DATA_H_

