/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef STRUCTS_TYPEDEFS_H_
#define STRUCTS_TYPEDEFS_H_

typedef struct who_data WHO_DATA;
typedef struct last_data LAST_DATA;
typedef struct complain_data COMPLAIN_DATA;
typedef struct ban_data BAN_DATA;
typedef struct season_data SEASON_DATA;
typedef struct hour_min_sec HOUR_MIN_SEC;
typedef struct wizent WIZENT;
typedef struct for_data FOR_DATA;
typedef struct rat_data RAT_DATA;
typedef struct descriptor_data DESCRIPTOR_DATA;
typedef struct helps_file HELPS_FILE;
typedef struct help_data HELP_DATA;
typedef struct shop_data SHOP_DATA;
typedef struct repairshop_data REPAIR_DATA;
typedef struct mob_prog_act_list MPROG_ACT_LIST;
typedef struct mob_prog_data MPROG_DATA;
typedef struct script_data SCRIPT_DATA;
typedef struct race_data RACE_DATA;
typedef struct lcnv_data LCNV_DATA;
typedef struct lang_data LANG_DATA;
typedef struct known_lang KNOWN_LANG;
typedef struct madule_data MODULE_DATA;
typedef struct star_data STAR_DATA;
typedef struct moon_data MOON_DATA;
typedef struct dock_data DOCK_DATA;
typedef struct crew_data CREW_DATA;
typedef struct shipdock_data SHIPDOCK_DATA;
typedef struct hangar_data HANGAR_DATA;
typedef struct transponder_data TRANSPONDER_DATA;
typedef struct smap_data SMAP_DATA;
typedef struct space_data SPACE_DATA;
typedef struct bounty_data BOUNTY_DATA;
typedef struct inform_data INFORM_DATA;
typedef struct guard_data GUARD_DATA;
typedef struct planet_data PLANET_DATA;
typedef struct member_data MEMBER_DATA;
typedef struct politics_data POLITICS_DATA;
typedef struct hq_room_desc HQ_ROOM_DESC;
typedef struct hq_room HQ_ROOM;
typedef struct hq_data HQ_DATA;
typedef struct clan_data CLAN_DATA;
typedef struct course_data COURSE_DATA;
typedef struct turret_data TURRET_DATA;
typedef struct ship_data SHIP_DATA;
typedef struct cargo_data CARGO_DATA;
typedef struct material_data MATERIAL_DATA;
typedef struct warehouse_data WAREHOUSE_DATA;
typedef struct astro_data ASTRO_DATA;
typedef struct missile_data MISSILE_DATA;
typedef struct turbocar_data TURBOCAR;
typedef struct tc_station TC_STATION;
typedef struct tourney_data TOURNEY_DATA;
typedef struct note_data NOTE_DATA;
typedef struct board_data BOARD_DATA;
typedef struct affect_data AFFECT_DATA;
typedef struct smaug_affect SMAUG_AFF;
typedef struct requirement_data REQUIREMENT_DATA;
typedef struct ilist_data ILD;
typedef struct timer_data TIMER;
typedef struct quest_index_data QUEST_INDEX_DATA;
typedef struct quest_data QUEST_DATA;
typedef struct chapter_index_data CHAPTER_INDEX_DATA;
typedef struct chapter_data CHAPTER_DATA;
typedef struct q_command_data QUEST_CMND_DATA;
typedef struct q_action_data QUEST_ACTION_DATA;
typedef struct event_data EVENT_DATA;
typedef struct quest_mob_data QUEST_MOB_DATA;
typedef struct quest_obj_data QUEST_OBJ_DATA;
typedef struct component_data COMPONENT_DATA;
typedef struct part_data PART_DATA;
typedef struct project_data PROJECT_DATA;
typedef struct mob_index_data MOB_INDEX_DATA;
typedef struct cloning_data CLONING_DATA;
typedef struct cloning_tmp_data CLONING_TMP_DATA;
typedef struct ship_index_data SHIP_INDEX_DATA;
typedef struct ship_room_data SHIP_ROOM_DATA;
typedef struct ship_exit_data SHIP_EXIT_DATA;
typedef struct nameslist_data NAMESLIST_DATA;
typedef struct hunt_hate_fear HHF_DATA;
typedef struct fighting_data FIGHT_DATA;
typedef struct extracted_char_data EXTRACT_CHAR_DATA;
typedef struct crime_data CRIME_DATA;
typedef struct suspect_data SUSPECT_DATA;
typedef struct alias_data ALIAS_DATA;
typedef struct var_data VAR_DATA;
typedef struct fevent_data FEVENT_DATA;
typedef struct known_char_data KNOWN_CHAR_DATA;
typedef struct dialog_data DIALOG_DATA;
typedef struct dialog_node DIALOG_NODE;
typedef struct char_data CHAR_DATA;
typedef struct killed_data KILLED_DATA;
typedef struct pc_data PC_DATA;
typedef struct extra_descr_data EXTRA_DESCR_DATA;
typedef struct obj_index_data OBJ_INDEX_DATA;
typedef struct obj_data OBJ_DATA;
typedef struct exit_data EXIT_DATA;
typedef struct reset_data RESET_DATA;
typedef struct area_data AREA_DATA;
typedef struct area_tmp_data AREA_TMP_DATA;
typedef struct godlist_data GOD_DATA;
typedef struct system_data SYSTEM_DATA;
typedef struct room_index_data ROOM_INDEX_DATA;
typedef struct teleport_data TELEPORT_DATA;
typedef struct skill_type SKILLTYPE;
typedef struct auction_data AUCTION_DATA;
typedef struct bets_progres BETS_PROGRES;
typedef struct stock_exchange_data STOCK_EXCHANGE_DATA;
typedef struct deposit_data DEPOSIT_DATA;
typedef struct cmd_type CMDTYPE;
typedef struct social_type SOCIALTYPE;

#endif //STRUCTS_TYPEDEFS_H_

