/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef AREA_DATA_H_
#define AREA_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	area_data
{
	AREA_DATA			* next;
	AREA_DATA			* prev;
	AREA_DATA			* next_sort;
	AREA_DATA			* prev_sort;
	PLANET_DATA			* planet;
	AREA_DATA			* next_on_planet;
	AREA_DATA			* prev_on_planet;
	char				* name;
	char				* filename;
	int64				flags;
	int					security;
	int					status;	 /* h, 8/11 */
	int					age;
	int					nplayer;
	int					reset_frequency;
	int					lvnum;
	int					uvnum;
	int					low_range;
	int					high_range;
	char				* author; /* Scryn */
	char				* builder; //byTrog
	char				* resetmsg; /* Rennard */
	RESET_DATA			* last_mob_reset;
	RESET_DATA			* last_obj_reset;
	int					max_players;
	int					mkills;
	int					mdeaths;
	int					pkills;
	int					pdeaths;
	int					gold_looted;
	int					illegal_pk;
	int					high_economy;
	int					low_economy;
	QUEST_INDEX_DATA	* quest;			// Added by Thanos
	bool				Envy;		/* Do czytania krain Envy */
	int					area_id;
	AREA_TMP_DATA		*area_tmp;
};

#endif //AREA_DATA_H_

