/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef AREA_TMP_DATA_H_
#define AREA_TMP_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	area_tmp_data
{
	MID		*first_mob;
	MID		*last_mob;
	OID		*first_obj;
	OID		*last_obj;
	RID		*first_room;
	RID		*last_room;
	SHD		*first_shop;
	SHD		*last_shop;
	RHD		*first_repair;
	RHD		*last_repair;
};

#endif //AREA_TMP_DATA_H_

