/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef CARGO_DATA_H_
#define CARGO_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct cargo_data
{
	CARGO_DATA			* next;
	CARGO_DATA			* prev;
	int					amount;
	int					type;
	int					prise;
	int					quality;
	MATERIAL_DATA		* pMaterial;
};

#endif //CARGO_DATA_H_

