/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef CLONING_TMP_DATA_H_
#define CLONING_TMP_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct cloning_tmp_data
{
	int		top_level;
	int		skill_level[MAX_ABILITY];
	int		experience[MAX_ABILITY];
	long	credits;
};

#endif //CLONING_TMP_DATA_H_

