/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef CMD_TYPE_H_
#define CMD_TYPE_H_
#include "../defines.h"
#include "../typedefs.h"

struct	cmd_type
{
	CMDTYPE				* next;
	char				* name;
	char				* alias; /* open/otwórz, backstab/bs itd. -- Thanos */
	DO_FUN				* do_fun;
	int					position;
	int					level;
	int					log;
	int64				flags;	/* Thanos - flagi komendy np. ukryta */
	struct				timerset	userec;
};

#endif //CMD_TYPE_H_

