/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef CRIME_DATA_H_
#define CRIME_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct crime_data
{
	CRIME_DATA			* next;
	CRIME_DATA			* prev;
	char				* planet;
	int					level;
	int					type;
	int					jail_vnum;
	int					jail_end;
	int					released;
};

#endif //CRIME_DATA_H_

