/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef DESCRIPTOR_DATA_H_
#define DESCRIPTOR_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	descriptor_data
{
	DESCRIPTOR_DATA		* next;
	DESCRIPTOR_DATA		* prev;
	DESCRIPTOR_DATA		* snoop_by;
	CHAR_DATA			* character;
	CHAR_DATA			* tmp_ch;		//do rename (Thanos)
	CHAR_DATA			* original;
	char				* host;
	char				* hostip;
	uint16_t			port;
	int					descriptor;
	int					connected;
	int					idle;
	int					lines;
	bool				fcommand;
	char				inbuf	[MAX_INBUF_SIZE];
	char				incomm	[MAX_INPUT_LENGTH];
	char				inlast	[MAX_INPUT_LENGTH];
	int					repeat;
	char				* outbuf;
	unsigned long		outsize;
	int					outtop;
	char				* pagebuf;
	unsigned long		pagesize;
	int					pagetop;
	char				* pagepoint;
	char				pagecmd;
	char				pagecolor;
	int					auth_inc;
	int					auth_state;
	char				abuf[ 256 ];
	int					auth_fd;
	char				* user;
	int					atimes;
	int					newstate;
	unsigned char		prevcolor;
	int					pass_try;//Added by Thanos (maxymalna ilosc pomylek z haslem)
	void				* olc_editing;//Added by Thanos (OLC)
	char				** str_editing; /* do nowego edytora */
	bool				ipv6;
};

#endif //DESCRIPTOR_DATA_H_
