/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef HELP_DATA_H_
#define HELP_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	help_data
{
	HELPS_FILE			* file;
	HELP_DATA			* next;
	HELP_DATA			* prev;
	int					level;
	int					type;
	char				* keyword;
	char				* syntax;
	char				* text;
};

#endif //HELP_DATA_H_

