/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef HQ_ROOM_H_
#define HQ_ROOM_H_
#include "../defines.h"
#include "../typedefs.h"

struct	hq_room
{
	hq_room_type		type;
	hq_room_state		state;
	time_t				completion_date;	/* time at which building of room will be completed */
	int					damaged;			/* % damaged */
};

#endif //HQ_ROOM_H_

