/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef MISSILE_DATA_H_
#define MISSILE_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct missile_data
{
	MISSILE_DATA		* next;
	MISSILE_DATA		* prev;
	MISSILE_DATA		* next_in_starsystem;
	MISSILE_DATA		* prev_in_starsystem;
	SPACE_DATA			* starsystem;
	SHIP_DATA			* target;
	SHIP_DATA			* fired_from;
	char				* fired_by;
	int					missiletype;
	int					age;
	int					speed;
	int					mx, my, mz;
};

#endif //MISSILE_DATA_H_

