/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef MOB_INDEX_DATA_H_
#define MOB_INDEX_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	mob_index_data
{
	MOB_INDEX_DATA		* next;
	MOB_INDEX_DATA		* next_sort;
	SPEC_FUN			* spec_fun;
	SPEC_FUN			* spec_2;
	SHOP_DATA			* pShop;
	REPAIR_DATA			* rShop;
	MPROG_DATA			* mudprogs;
	NAMESLIST_DATA		* first_nameslist;
	NAMESLIST_DATA		* last_nameslist;
	NAMESLIST_DATA		* nameslist;
	AREA_DATA			* in_area;
	RACE_DATA			* race;
	int					namescount;
	int64				progtypes;
	char				* przypadki[6]; //added by Thanos (Ratma)
	char				* inflectsFemale[6];	// Pixel: przypadkiF
	char				* player_name;
	char				* long_descr;
	char				* description;
	int					vnum;
	int					count;
	int					killed;
	int					sex;
	int					level;
	int64				act;
	int64				affected_by;
	int					alignment;
	int					mobthac0;		/* Unused */
	int					ac;
	int					hitnodice;
	int					hitsizedice;
	int					hitplus;
	int					damnodice;
	int					damsizedice;
	int					damplus;
	int					numattacks;
	int					gold;
	int					exp;
	int64				xflags;
	int64				resistant;
	int64				immune;
	int64				susceptible;
	int64				attacks;
	int64				defenses;
	LANG_DATA			* speaking;
	int					position;
	int					defposition;
	int					height;
	int					weight;
	int					hitroll;
	int					damroll;
	int					perm_str;
	int					perm_int;
	int					perm_wis;
	int					perm_dex;
	int					perm_con;
	int					perm_cha;
	int					perm_lck;
	int					perm_frc;
	int					saving_poison_death;
	int					saving_wand;
	int					saving_para_petri;
	int					saving_breath;
	int					saving_spell_staff;
	char				* s_vip_flags;	//Thanosowe
	char				* dialog_name;
};

#endif //MOB_INDEX_DATA_H_

