/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef MOB_PROG_DATA_H_
#define MOB_PROG_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	mob_prog_data
{
	MPROG_DATA			* next;
	int64				type;
	bool				triggered;
	int					resetdelay;
	char				* arglist;
	char				* comlist;
};

#endif //MOB_PROG_DATA_H_

