/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef PART_DATA_H_
#define PART_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct part_data
{
	PART_DATA			* next;
	PART_DATA			* prev;
	COMPONENT_DATA		* first_component;
	COMPONENT_DATA		* last_component;
	int					quantity;
};

#endif //PART_DATA_H_

