/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef PROJECT_DATA_H_
#define PROJECT_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct project_data
{
	PROJECT_DATA		* next;
	PROJECT_DATA		* prev;
	PART_DATA			* first_part;
	PART_DATA			* last_part;
	OBJ_INDEX_DATA		* effect;
	OBJ_INDEX_DATA		* formula;
	int					montage_type;
};

#endif //PROJECT_DATA_H_

