/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef QUEST_DATA_H_
#define QUEST_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	quest_data
{
	QUEST_DATA			* next;
	QUEST_DATA			* prev;
	QUEST_INDEX_DATA	* pIndexData;
	CHAPTER_DATA		* first_chapter;
	CHAPTER_DATA		* last_chapter;
	CHAPTER_DATA		* curr_chapter;
	QUEST_MOB_DATA		* first_mob;
	QUEST_MOB_DATA		* last_mob;
	QUEST_OBJ_DATA		* first_obj;
	QUEST_OBJ_DATA *	last_obj;
	CHAR_DATA *			player;
	bool				finished;
	bool				failed;		/*czy siê nie skoñczy³ za czas*/
	time_t				logon;		/*o której zosta³ odpalony/wznowiony*/
	int					time_took;	/*ile zaj±³ przedtem czasu */
	int					curr_qp;
	QUEST_CMND_DATA		* first_init_cmd;
	QUEST_CMND_DATA		* last_init_cmd;
	QUEST_ACTION_DATA	* first_action;
	QUEST_ACTION_DATA	* last_action;
};

#endif //QUEST_DATA_H_

