/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef QUEST_INDEX_DATA_H_
#define QUEST_INDEX_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	quest_index_data
{
	QUEST_INDEX_DATA	* next;
	QUEST_INDEX_DATA	* prev;
	char				* name;		/* nazwa */
	char				* author;		/* nazwa */
	char				* description;	/* opis	 */
	int64				flags;		/* flagi */
	int					quest_id;	/* vnum questa */
	int					min_lev;	/* ograniczniki levelowe */
	int					max_lev;
	int					questor;	/* vnum moba daj±cego quest */
	int					time;		/* ile czasu (w godzinach) */
	int					penalty;	/* kara w exp */
	int					security;
	CHAPTER_INDEX_DATA	* first_chapter;	/* wska¼niki na rozdzia³y questa */
	CHAPTER_INDEX_DATA	* last_chapter;
	QUEST_CMND_DATA		* first_init_cmd;
	QUEST_CMND_DATA		* last_init_cmd;
	QUEST_ACTION_DATA	* first_action;
	QUEST_ACTION_DATA	* last_action;
};

#endif //QUEST_INDEX_DATA_H_

