/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef RAT_DATA_H_
#define RAT_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct rat_data
{
	CHAR_DATA			* rOwner;		// wska¼nik na wykonawcê 'rat'
	int					rRoom;		// vnum pokoju aktualnie 'obs³ugiwanego'
	char				* command;	// komenda
	int					Start;		// vnum lokacji pocz±tkowej
	int					End;		// vnum lokacji koñcowej
	bool				rStopped;	// czy zatrzymana
	int					rCount;		// ilo¶æ powtórzeñ
};

#endif //RAT_DATA_H_

