/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef SEASON_DATA_H_
#define SEASON_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct	season_data
{
	SEASON_DATA			* next;
	SEASON_DATA			* prev;
	char				* name;			/* nazwa pory */
	int					mmhg;			/* srednie cisnienie */
	int					diff_mmhg;		/* dopuszczalne odchylenie */
	int					temperature;	/* srednia temperatura */
	int					diff_temperature;/* dopuszczalne odchylenie */
	int					windspeed;		/* predkosc wiatru */
	int					night_length;	/* dlugosc nocy */
	int					day_length;		/* dlugosc dnia */
	int					length;			/* dlugosc pory (miesiace)*/
};

#endif //SEASON_DATA_H_

