/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef SHIP_INDEX_DATA_H_
#define SHIP_INDEX_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct ship_index_data
{
	SHIP_INDEX_DATA		* next;
	SHIP_INDEX_DATA		* prev;
	char				* name;
	char				* builders;
	int					security;
	int					roomcount;	//dla wygody
	int					resetcount;	//równie¿
	SHIP_ROOM_DATA		* first_room;
	SHIP_ROOM_DATA		* last_room;
	int					vnum;
	int					first_dumped;	//olc
	int					last_dumped;
	int					count;		// ile egzemplarzy za³adowano z wzorca
	TURRET_DATA			* first_turret;
	TURRET_DATA			* last_turret;
	HANGAR_DATA			* first_hangar;
	HANGAR_DATA			* last_hangar;
	CARGO_DATA			* first_cargo;
	CARGO_DATA			* last_cargo;
	MODULE_DATA			* first_module;
	MODULE_DATA			* last_module;
	SMAP_DATA			* first_smap;
	SMAP_DATA			* last_smap;
	SHIPDOCK_DATA		* first_dock;
	SHIPDOCK_DATA		* last_dock;
	int					maxmodule;
	char				* filename;
	char				* description;
	int					type;
	int					clazz;
	int					comm;
	int					sensor;
	int					astro_array;
	int					target_array;
	float				hyperspeed;
	float				realspeed;
	int					missiletype;
	int					missilestate;
	int					maxmissiles;
	int					maxtorpedos;
	int					maxrockets;
	int					lasers;
	int					ioncannons;
	int					tractorbeam;
	int					manuever;
	int					maxenergy;
	int					maxshield;
	int					maxhull;
	int					cockpit;
	int					shipyard;
	int					entrance;
	int					engineroom;
	int					navseat;
	int					pilotseat;
	int					coseat;
	int					gunseat;
	int					maxinterdict;
	int					trawler;//Aldegard
	int					maxcloack;
	int					maxchaff;
	int					maxcargo;//Aldegard from snipet
	float				size;//urealnienie radar i look
	int					version;
	int64				flags;
	int					level;
};

#endif //SHIP_INDEX_DATA_H_

