/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef SHIPDOCK_DATA_H_
#define SHIPDOCK_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct shipdock_data
{
	SHIPDOCK_DATA		* next;
	SHIPDOCK_DATA		* prev;
	int					type;
	int					vnum;
	int					status;
	int					opentimer;
	SHIP_DATA			* target;
	int					targetvnum;
	int					master_slave;//0 - slave czyli to on przybil 1 - master do niego zacumowano
};

#endif //SHIPDOCK_DATA_H_

