/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef SHIP_ROOM_DATA_H_
#define SHIP_ROOM_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct ship_room_data
{
	SHIP_ROOM_DATA		* next;
	SHIP_ROOM_DATA		* prev;
	EXTRA_DESCR_DATA	* first_extradesc;
	EXTRA_DESCR_DATA	* last_extradesc;
	SHIP_EXIT_DATA		* first_exit;
	SHIP_EXIT_DATA		* last_exit;
	RESET_DATA			* first_reset;
	RESET_DATA			* last_reset;
	char				* name;
	char				* description;
	int					vnum;
	int64				room_flags;
	MPROG_DATA			* mudprogs;
	int64				progtypes;
	int					light;
	int					sector_type;
	int					tele_vnum;
	int					tele_delay;
	int					tunnel;
};

#endif //SHIP_ROOM_DATA_H_

