/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef SOCIAL_TYPE_H_
#define SOCIAL_TYPE_H_
#include "../defines.h"
#include "../typedefs.h"

struct	social_type
{
	SOCIALTYPE			* next;
	char				* name;
	char				* char_no_arg;
	char				* others_no_arg;
	char				* char_found;
	char				* others_found;
	char				* vict_found;
	char				* char_auto;
	char				* others_auto;
};

#endif //SOCIAL_TYPE_H_

