/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef STAR_DATA_H_
#define STAR_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct star_data
{
	STAR_DATA			* next;
	STAR_DATA			* prev;
	char				* name;
	float				xpos;
	float				ypos;
	float				zpos;
	int					type;
	float				gravity;
	float				radius;
	float				star_radius;
	float				star_radius2;
};

#endif //STAR_DATA_H_

