/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef TRANSPONDER_DATA_H_
#define TRANSPONDER_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct transponder_data
{
	TRANSPONDER_DATA	* next;
	TRANSPONDER_DATA	* prev;
	char				* number;
	char				* shipname;
	int					shipclas;
};

#endif //TRANSPONDER_DATA_H_

