/***************************************************************************
* swmud.pl
* ------------------------------------------------------------------------ *
*                     ____________   __     ______                         *
*   Aldegard    Jot  (   ___   ___| /  \   |  __  )   Thanos      Trog     *
*        ______________\  \|   |  /  ^   \ |     <_______________          *
*        \________________/|___|/___/"\___\|__|\________________/          *
*                  \   \/ \/   //  \   |  __  )(  ___/`                    *
*                    \       //  ^   \ |     <__)  \                       *
*                      \_!_//___/"\___\|__|\______/TM                      *
* (c) 2009                  M       U        D                Ver 1.0      *
* ------------------------------------------------------------------------ *
*                               <module_name>                              *
****************************************************************************/


/* This file was generated by Trog's granulate_structs.pl. */

#ifndef WAREHOUSE_DATA_H_
#define WAREHOUSE_DATA_H_
#include "../defines.h"
#include "../typedefs.h"

struct warehouse_data
{
	int				max_capacity;
	int				current_capacity;
	int				materials_count;
	CARGO_DATA		* first_cargo;
	CARGO_DATA		* last_cargo;
};

#endif //WAREHOUSE_DATA_H_

